### PR TITLE
[PY3] Make jumeg Python 3.7 compatible. 

### PR DESCRIPTION
**Pull request by pravsripad**
With this PR, jumeg will be Python 3.7 compatible and has been setup as a package for ease of installation and use. 

The major changes are:
1. PY3 compatibility using 2to3. 
2. Changes in the jumeg directory structure to make it into a python package. 
3. Lots of changes to make it mne-python v0.18 friendly. 

The upgrades break some of our old functionality and needs to be fixed. 

For the testing phase, I suggesting the following:
1. Make fresh install of anaconda py3.7 environment using the environment file attached with the commands below.
[environment_jumeg_test.txt](https://github.com/jdammers/jumeg/files/2851907/environment_jumeg_test.txt)

```
conda env create -f environment_jumeg_test.txt
conda activate jumeg
```

2. Examples can be downloaded from here and tested. 
[jumeg_examples.zip](https://github.com/jdammers/jumeg/files/2851929/jumeg_examples.zip)

I'll include the known issues I have faced in the comments below.

### CODE REVIEW

**Comment by pravsripad** [comment]
MFT related examples do not run, 

/examples/plot_perform_*

Maybe @ebeich can have a look.

**Comment by pravsripad** [comment]
ICA related examples fails with the below errors,
do_compare_ica_methods.py
plot_rank_estimation.py

```
psripad@pravmac:~/mne/jumeg/examples $python do_compare_ica_methods.py
Opening raw data file /Users/psripad/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif...
    Read a total of 3 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
    Range : 25800 ... 192599 =     42.956 ...   320.670 secs
Ready.
Current compensation grade : 0
Reading 0 ... 166799  =      0.000 ...   277.714 secs...
Setting up band-pass filter from 1 - 45 Hz
l_trans_bandwidth chosen to be 1.0 Hz
h_trans_bandwidth chosen to be 11.2 Hz
Filter length of 1983 samples (3.302 sec) selected
[Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done  14 tasks      | elapsed:    0.9s
[Parallel(n_jobs=2)]: Done 366 out of 366 | elapsed:    7.2s finished
Fitting ICA to data using 305 channels (please be patient, this may take a while)
Inferring max_pca_components from picks
Selection by number: 60 components
/Users/psripad/miniconda3/lib/python3.7/site-packages/sklearn/decomposition/fastica_.py:121: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  ConvergenceWarning)
Fitting ICA took 221.9s.
Traceback (most recent call last):
  File "do_compare_ica_methods.py", line 42, in <module>
    pca_pre_whitener_filt_mne = ica_mne._pre_whitener.copy()  # this is the standard deviation of MEG channels
AttributeError: 'ICA' object has no attribute '_pre_whitener'
```

```
psripad@pravmac:~/mne/jumeg/examples $python plot_rank_estimation.py
Opening raw data file /Users/psripad/mne_data/MNE-sample-data/MEG/sample/sample_audvis_filt-0-40_raw.fif...
    Read a total of 4 projection items:
        PCA-v1 (1 x 102)  idle
        PCA-v2 (1 x 102)  idle
        PCA-v3 (1 x 102)  idle
        Average EEG reference (1 x 60)  idle
    Range : 6450 ... 48149 =     42.956 ...   320.665 secs
Ready.
Current compensation grade : 0
Traceback (most recent call last):
  File "plot_rank_estimation.py", line 29, in <module>
    rank_all, rank_median = rank_estimation(data)
  File "/Users/psripad/miniconda3/lib/python3.7/site-packages/jumeg/jumeg_utils.py", line 1356, in rank_estimation
    data_w, pca = whitening(data.T)
  File "/Users/psripad/miniconda3/lib/python3.7/site-packages/jumeg/decompose/ica.py", line 288, in whitening
    from sklearn.decomposition import RandomizedPCA
ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition' (/Users/psripad/miniconda3/lib/python3.7/site-packages/sklearn/decomposition/__init__.py)
```

@jdammers @ckiefer0 ?

**Comment by pravsripad** [comment]
Example plot_test_transform_mni_to_ras.py fails with, 
```
psripad@pravmac:~/mne/jumeg/examples $python plot_test_transform_mni_to_ras.py
To plot a vertex point, convert it to MNI coordinates and then reconvert it back to RAS to obtain the vertex number.
It works when 'fsaverage' subject is used, but does not when any other subjects are used.
Traceback (most recent call last):
  File "plot_test_transform_mni_to_ras.py", line 23, in <module>
    new_stc = mne.morph_data('sample', 'fsaverage', stc, grade=5, subjects_dir=subjects_dir, n_jobs=2)
AttributeError: module 'mne' has no attribute 'morph_data'
```
This is due to an API change, I'll fix this one.

**Comment by jdammers** [comment]
> ICA related examples fails with the below errors,
> do_compare_ica_methods.py
> plot_rank_estimation.py
> 
> ```
> psripad@pravmac:~/mne/jumeg/examples $python do_compare_ica_methods.py
> Opening raw data file /Users/psripad/mne_data/MNE-sample-data/MEG/sample/sample_audvis_raw.fif...
>     Read a total of 3 projection items:
>         PCA-v1 (1 x 102)  idle
>         PCA-v2 (1 x 102)  idle
>         PCA-v3 (1 x 102)  idle
>     Range : 25800 ... 192599 =     42.956 ...   320.670 secs
> Ready.
> Current compensation grade : 0
> Reading 0 ... 166799  =      0.000 ...   277.714 secs...
> Setting up band-pass filter from 1 - 45 Hz
> l_trans_bandwidth chosen to be 1.0 Hz
> h_trans_bandwidth chosen to be 11.2 Hz
> Filter length of 1983 samples (3.302 sec) selected
> [Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
> [Parallel(n_jobs=2)]: Done  14 tasks      | elapsed:    0.9s
> [Parallel(n_jobs=2)]: Done 366 out of 366 | elapsed:    7.2s finished
> Fitting ICA to data using 305 channels (please be patient, this may take a while)
> Inferring max_pca_components from picks
> Selection by number: 60 components
> /Users/psripad/miniconda3/lib/python3.7/site-packages/sklearn/decomposition/fastica_.py:121: ConvergenceWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
>   ConvergenceWarning)
> Fitting ICA took 221.9s.
> Traceback (most recent call last):
>   File "do_compare_ica_methods.py", line 42, in <module>
>     pca_pre_whitener_filt_mne = ica_mne._pre_whitener.copy()  # this is the standard deviation of MEG channels
> AttributeError: 'ICA' object has no attribute '_pre_whitener'
> ```
> 
> ```
> psripad@pravmac:~/mne/jumeg/examples $python plot_rank_estimation.py
> Opening raw data file /Users/psripad/mne_data/MNE-sample-data/MEG/sample/sample_audvis_filt-0-40_raw.fif...
>     Read a total of 4 projection items:
>         PCA-v1 (1 x 102)  idle
>         PCA-v2 (1 x 102)  idle
>         PCA-v3 (1 x 102)  idle
>         Average EEG reference (1 x 60)  idle
>     Range : 6450 ... 48149 =     42.956 ...   320.665 secs
> Ready.
> Current compensation grade : 0
> Traceback (most recent call last):
>   File "plot_rank_estimation.py", line 29, in <module>
>     rank_all, rank_median = rank_estimation(data)
>   File "/Users/psripad/miniconda3/lib/python3.7/site-packages/jumeg/jumeg_utils.py", line 1356, in rank_estimation
>     data_w, pca = whitening(data.T)
>   File "/Users/psripad/miniconda3/lib/python3.7/site-packages/jumeg/decompose/ica.py", line 288, in whitening
>     from sklearn.decomposition import RandomizedPCA
> ImportError: cannot import name 'RandomizedPCA' from 'sklearn.decomposition' (/Users/psripad/miniconda3/lib/python3.7/site-packages/sklearn/decomposition/__init__.py)
> ```
> 
> @jdammers @ckiefer0 ?

I know the problem and have already applied fixes. I can push my version very soon.

**Comment by pravsripad** [comment]
> 
> I know the problem and have already applied fixes. I can push my version very soon.
Sounds good, then your fix can be applied once this branch is merged with master.

**Comment by pravsripad** [comment]
As discussed I am merging this so that jumeg master can be used with py3. 

Fixes for the below know issues will be applied on top. 
1. MFT related
2. 'RandomizedPCA' from 'sklearn.decomposition' - ImportError

To install the newest version using pip, do
```
pip install https://github.com/jdammers/jumeg/archive/master.zip
```

Download the older py2 friendly version from [here](https://github.com/jdammers/jumeg/archive/master.zip).

**Pull request merged**
